#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="/etc/incudal/pps-guard.conf"

if [[ ! -r "${CONFIG_FILE}" ]]; then
  echo "PPS config is not readable: ${CONFIG_FILE}" >&2
  exit 1
fi

PPS_MIN_LIMIT="${PPS_MIN_LIMIT:-20000}"
PPS_LIMIT="${PPS_LIMIT:-${PPS_MIN_LIMIT}}"
PPS_BURST_PACKETS="${PPS_BURST_PACKETS:-5000}"
PPS_SINGLE_TARGET_LIMIT="${PPS_SINGLE_TARGET_LIMIT:-${PPS_MIN_LIMIT}}"
PPS_SINGLE_TARGET_BURST="${PPS_SINGLE_TARGET_BURST:-2500}"
PPS_BLOCK_SECONDS="${PPS_BLOCK_SECONDS:-3600}"
PPS_OBSERVE_SECONDS="${PPS_OBSERVE_SECONDS:-120}"
BRIDGE_NAME="${BRIDGE_NAME:-}"

# The config is generated by the installer, but it is still input. Parse only
# the known KEY=value records instead of sourcing it as shell code.
while IFS= read -r line || [[ -n "${line}" ]]; do
  case "${line}" in
    PPS_MIN_LIMIT=*) PPS_MIN_LIMIT="${line#*=}" ;;
    PPS_LIMIT=*) PPS_LIMIT="${line#*=}" ;;
    PPS_BURST_PACKETS=*) PPS_BURST_PACKETS="${line#*=}" ;;
    PPS_SINGLE_TARGET_LIMIT=*) PPS_SINGLE_TARGET_LIMIT="${line#*=}" ;;
    PPS_SINGLE_TARGET_BURST=*) PPS_SINGLE_TARGET_BURST="${line#*=}" ;;
    PPS_BLOCK_SECONDS=*) PPS_BLOCK_SECONDS="${line#*=}" ;;
    PPS_OBSERVE_SECONDS=*) PPS_OBSERVE_SECONDS="${line#*=}" ;;
    BRIDGE_NAME=*) BRIDGE_NAME="${line#*=}" ;;
  esac
done < "${CONFIG_FILE}"

PPS_MIN_LIMIT=20000
if ! [[ "${BRIDGE_NAME}" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]]; then
  echo "Invalid BRIDGE_NAME" >&2
  exit 1
fi

if ! [[ "${PPS_LIMIT}" =~ ^[0-9]+$ ]] || (( PPS_LIMIT < PPS_MIN_LIMIT || PPS_LIMIT > 500000 )); then
  PPS_LIMIT="${PPS_MIN_LIMIT}"
fi
if ! [[ "${PPS_SINGLE_TARGET_LIMIT}" =~ ^[0-9]+$ ]] || (( PPS_SINGLE_TARGET_LIMIT < PPS_MIN_LIMIT || PPS_SINGLE_TARGET_LIMIT > 500000 )); then
  PPS_SINGLE_TARGET_LIMIT="${PPS_MIN_LIMIT}"
fi
if ! [[ "${PPS_BURST_PACKETS}" =~ ^[1-9][0-9]*$ ]] || (( PPS_BURST_PACKETS > 5000000 )); then
  PPS_BURST_PACKETS=5000
fi
if ! [[ "${PPS_SINGLE_TARGET_BURST}" =~ ^[1-9][0-9]*$ ]] || (( PPS_SINGLE_TARGET_BURST > 5000000 )); then
  PPS_SINGLE_TARGET_BURST=2500
fi
if ! [[ "${PPS_BLOCK_SECONDS}" =~ ^[1-9][0-9]*$ ]] || (( PPS_BLOCK_SECONDS > 86400 )); then
  PPS_BLOCK_SECONDS=3600
fi
if ! [[ "${PPS_OBSERVE_SECONDS}" =~ ^[1-9][0-9]*$ ]] || (( PPS_OBSERVE_SECONDS > 86400 )); then
  PPS_OBSERVE_SECONDS=120
fi

# Build the delete and replacement in one nft transaction. Removing the
# existing table in a separate command creates a window with no PPS guard
# when validation or loading of the new rules fails.
DELETE_TABLE=""
if nft list table inet incudal_pps_guard >/dev/null 2>&1; then
  DELETE_TABLE="delete table inet incudal_pps_guard"
fi

nft -f - <<EOF
${DELETE_TABLE}
table inet incudal_pps_guard {
  set blocked_v4 {
    type ether_addr . ipv4_addr
    flags timeout
    timeout ${PPS_BLOCK_SECONDS}s
  }
  set blocked_v6 {
    type ether_addr . ipv6_addr
    flags timeout
    timeout ${PPS_BLOCK_SECONDS}s
  }
  set observed_v4 {
    type ether_addr . ipv4_addr
    flags timeout
    timeout ${PPS_OBSERVE_SECONDS}s
  }
  set observed_v6 {
    type ether_addr . ipv6_addr
    flags timeout
    timeout ${PPS_OBSERVE_SECONDS}s
  }
  chain instance_pps_limit {
    meter per_instance_pps { ether saddr limit rate over ${PPS_LIMIT}/second burst ${PPS_BURST_PACKETS} packets } counter drop
  }
  chain forward {
    type filter hook forward priority -200; policy accept;
    iifname "${BRIDGE_NAME}" ether saddr . ip daddr @blocked_v4 counter drop
    iifname "${BRIDGE_NAME}" ether saddr . ip6 daddr @blocked_v6 counter drop
    iifname "${BRIDGE_NAME}" meta l4proto udp meter per_target_udp_v4 { ether saddr . ip daddr limit rate over ${PPS_SINGLE_TARGET_LIMIT}/second burst ${PPS_SINGLE_TARGET_BURST} packets } update @observed_v4 { ether saddr . ip daddr timeout ${PPS_OBSERVE_SECONDS}s } counter
    iifname "${BRIDGE_NAME}" meta l4proto tcp tcp flags & (syn | ack) == syn meter per_target_syn_v4 { ether saddr . ip daddr limit rate over ${PPS_SINGLE_TARGET_LIMIT}/second burst ${PPS_SINGLE_TARGET_BURST} packets } update @blocked_v4 { ether saddr . ip daddr timeout ${PPS_BLOCK_SECONDS}s } log prefix "INCUDAL_PPS_V4 " counter drop
    iifname "${BRIDGE_NAME}" meta l4proto udp meter per_target_udp_v6 { ether saddr . ip6 daddr limit rate over ${PPS_SINGLE_TARGET_LIMIT}/second burst ${PPS_SINGLE_TARGET_BURST} packets } update @observed_v6 { ether saddr . ip6 daddr timeout ${PPS_OBSERVE_SECONDS}s } counter
    iifname "${BRIDGE_NAME}" meta l4proto tcp tcp flags & (syn | ack) == syn meter per_target_syn_v6 { ether saddr . ip6 daddr limit rate over ${PPS_SINGLE_TARGET_LIMIT}/second burst ${PPS_SINGLE_TARGET_BURST} packets } update @blocked_v6 { ether saddr . ip6 daddr timeout ${PPS_BLOCK_SECONDS}s } log prefix "INCUDAL_PPS_V6 " counter drop
    iifname "${BRIDGE_NAME}" meta l4proto udp jump instance_pps_limit
    iifname "${BRIDGE_NAME}" meta l4proto tcp tcp flags & (syn | ack) == syn jump instance_pps_limit
  }
}
EOF
